### 2번 요청 스펙
GET http://localhost:8080/report/v2

## 응답 스펙
{
  "success": true,
  "code": 200,
  "message": "SUCCESS",
  "data": {
    "최저가": {
      "브랜드": "D",
      "카테고리": [
        {
          "카테고리": "가방",
          "가격": 2500
        },
        {
          "카테고리": "모자",
          "가격": 1500
        },
        {
          "카테고리": "바지",
          "가격": 3000
        },
        {
          "카테고리": "상의",
          "가격": 10100
        },
        {
          "카테고리": "스니커즈",
          "가격": 9500
        },
        {
          "카테고리": "아우터",
          "가격": 5100
        },
        {
          "카테고리": "액세서리",
          "가격": 2000
        },
        {
          "카테고리": "양말",
          "가격": 2400
        }
      ],
      "총액": 36100
    }
  },
  "timestamp": "2024-10-28T20:19:37.134907"
}