//**상품 추가 정책**
//상품 추가시, action, entityType, product 정보(name, price, brand.name, category.name)은 필수로 지정해야 한다.
//상품 추가시, 카테고리명, 브랜드명이 존재하지 않으면 실패한다.
//상품 추가시, 이미 존재하면 갱신되지않고 추가 요청이 실패처리된다.

//**상품 변경 정책**
//상품 변경시, 갱신대상은 id가되며, 기타 나머지 상품정보를 모두 입력해야한다.(포멧은 아래 정책에서 정의)
//상품 변경시, action, entityType, product 정보(id, name, price, brand.name, category.name)은 필수로 지정해야 한다.
//상품 추가시, 카테고리명, 브랜드명이 존재하지 않으면 실패한다.
//상품 추가시, 이미 존재하지 않으면 요청이 실패처리된다.

//**상품 삭제 정책**
//상품 삭제시, action, entityType, product 정보(id)는 필수로 지정해야 한다.
//실제 삭제가 아닌 소프트 삭제가 수행된다.(is_active 컬럼)

//(readme 작성 시 문제 노출 및 테스트 시 바로 정책 확인하기위해 해당 영역에 정리하였습니다.)

## 순서대로 진행해주세요!!!

### 1. 신규 상품 추가 성공
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"INSERT",
  "entityType":"PRODUCT",
  "data":{
    "name":"무신사 후드집업",
    "price": "1200",
    "brand": {
      "name":"A"
    },
    "category": {
      "name": "아우터"
    }
  }
}



### 2. 추가 실패 - 중복
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"INSERT",
  "entityType":"PRODUCT",
  "data":{
    "name":"무신사 후드집업",
    "price": "1200",
    "brand": {
      "name":"A"
    },
    "category": {
      "name": "아우터"
    }
  }
}

### 3. 추가 실패 - 가격 누락
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"INSERT",
  "entityType":"PRODUCT",
  "data":{
    "name":"무신사 후드집업",
    "brand": {
      "name":"A"
    },
    "category": {
      "name": "아우터"
    }
  }
}

### 4. 추가 실패 - 카테고리 누락
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"INSERT",
  "entityType":"PRODUCT",
  "data":{
    "name":"무신사 후드집업",
    "price": "1200",
    "brand": {
      "name":"A"
    },
    "category": {
    }
  }
}

### 5. 상품 변경 성공
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"UPDATE",
  "entityType":"PRODUCT",
  "data":{
    "id":1,
    "name":"무신사 후드집업",
    "price": "1200",
    "brand": {
      "name":"A"
    },
    "category": {
      "name": "아우터"
    }
  }
}

### 6. 상품 변경 실패 - 카테고리 부재
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"UPDATE",
  "entityType":"PRODUCT",
  "data":{
    "id":1,
    "name":"무신사 후드집업",
    "price": "1200",
    "brand": {
      "name":"A"
    }
  }
}

### 7. 상품 삭제 성공
POST localhost:9090/v1/manage/execute
Content-Type: application/json

{
  "action":"DELETE",
  "entityType":"PRODUCT",
  "data":{
    "id": 3
  }
}

### h2로 삭제 조회 가능합니다. http://localhost:9090/h2/login.jsp?jsessionid=c41efe04f2a7fffa25f1c42e9499251a
