server:
  port: 9090
spring:
  application:
    name: admin
  #h2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath*:db.h2/schema.sql
      data-locations: classpath*:db.h2/data.sql
      encoding: UTF-8

#swagger
springdoc:
  swagger-ui:
    enabled: true
app:
  title: MUSINSA ADMIN
  description: musinsa admin api
  version: v1.0.0

