spring:
  application:
    name: backend
  #h2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:musinsa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: never #always
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql
      encoding: UTF-8

#swagger
springdoc:
  swagger-ui:
    enabled: true
app:
  title: MUSINSA BACKEND
  description: musinsa backend api
  version: v1.0.0

#mybatis
#mybatis:
#  type-aliases-package: com.musinsa.backend
#  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: NULL

#logging
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
    com:
      musinsa:
        backend:
          mapper: DEBUG